# Generated by Django 2.2.7 on 2019-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbittracker', '0002_auto_20191107_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='actual',
            field=models.FloatField(null=True),
        ),
    ]
