# Generated by Django 2.2.7 on 2019-11-11 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbittracker', '0003_auto_20191107_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observed_habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
