# Generated by Django 2.2.7 on 2019-11-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbittracker', '0004_auto_20191111_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['date']},
        ),
    ]
