# Generated by Django 2.2.7 on 2019-11-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbittracker', '0005_auto_20191112_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='description',
        ),
    ]
